version: '2.4'

services:
  poster:
    image: poster
    container_name: poster
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "Australia/Brisbane"
      NODE_ENV: production
    volumes:
      - c:/docker/poster/randomthemes:/usr/src/app/public/randomthemes
      - c:/docker/poster/config:/usr/src/app/config
    ports:
      - 9876:3000

